### ISSUE TITLE
Make randomness seeded

### ISSUE THREAD

**Issue by dakrone** [elastic/rally-eventdata-track#4]
It'd be great if a seed could be specified for the `random` usage so that the same seed could be used to generate the same data between different runs.

**Comment by cdahlqvist** [comment]
At the moment I believe all the track code is run per worker process. If we seeded the randomness, would we be able to avoid all worker processes ending up generating exactly the same sequence of events?

@danielmitterdorfer Do you have any ideas how to best manage this within Rally itself or a track?

**Comment by danielmitterdorfer** [comment]
I think there are two aspects here:

1. Exposing the parameter sources' random seed to the outside. This could be done by using a (documented) parameter. All parameters get injected into the parameter source's constructor and can be used to seed `random`. This can be solved entirely within the scope of this track.
2. The second aspect is that we probably want to use a random seed by default and let the user override it from the outside in specific circumstances. This needs to be tackled in Rally. The related ticket is https://github.com/elastic/rally/issues/310. While it will not be available in Rally immediately, I plan to work on it soon.

So for the time being I think one option could be to implement aspect 1 in this track. Adapting it, once https://github.com/elastic/rally/issues/310 is available should not be that hard.

**Comment by danielmitterdorfer** [comment]
Support for providing track parameters from the command line has just landed in Rally master. 

There is a new command line parameter which you could use like this: `--track-params="random-seed:11"`. See the [PMC track](https://github.com/elastic/rally-tracks/blob/a3d5976db90cc1ded50c675c634a597d64c55a2a/pmc/challenges/default.json#L6) for an example on how to integrate that into a track.

**Comment by dakrone** [comment]
@danielmitterdorfer do you have an example of how to access the seed parameter from `track.py` rather than from the json?

**Comment by danielmitterdorfer** [comment]
Sure @dakrone. The first step is to inject the seed from the command line into the operation. E.g. You can use `--track-params="random-seed:11"` in `track.json` as follows:

```
{
  "name": "bulk-index-docs",
  "operation-type": "custom-bulk-index",
  "param-source": "custom-param-source",
  "bulk-size": 5000,
  "seed": {{ random-seed }}
}
```

This assumes that you have a custom parameter source and a custom runner. You should initialise the seed once per process in the parameter source's constructor using Python's [`random.seed`](https://docs.python.org/3.6/library/random.html#random.seed):

```python
import random

class CustomParamSource:
    def __init__(self, indices, params):
        self._indices = indices
        self._params = params
        random.seed(params.get("seed"))
```

This will keep the old behavior when no seed is specified (i.e. get will return `None`) but use your seed defined from the outside, if you define one.

Keep in mind that each client will initialise its seed identically. If you want to avoid it, you need to wait until, Rally calls `partition(self, partition_index, total_partitions)`. This method is called once per process for each client (index) and is used in Rally core to assign a slice of the data file(s) to bulk index to each client. If you have 4 clients, Rally would call:

* In client process with index 0: `custom_param_source.partition(0, 4)`
* ...
* In client process with index 3: `custom_param_source.partition(3, 4)`

You can use this to lazily initialise the random seed in that method instead to ensure each client has a different seed:

```python
import random

class CustomParamSource:
    def __init__(self, indices, params):
        self._indices = indices
        self._params = params
        

    def partition(self, partition_index, total_partitions):
        seed = partition_index * self._params["seed"] if "seed" in self._params else None
        random.seed(seed)
        return self
```

This is a bit more complex now because we cannot multiple an `int` with `None` hence the explicit check whether `"seed"` is contained in `self._params`.

According to the [docs](https://docs.python.org/3.6/library/random.html), Python's `random` implements the [Mersenne Twister PRNG algorithm](https://en.wikipedia.org/wiki/Mersenne_Twister). Unfortunately, I could not find any guidelines for "good" seeds so you should check whether the simple multiplication of the client index (or more abstract in the code: `partition_index`) with a constant seed is sufficient to get (a) long period length and (b) the periods of multiple clients do not overlap significantly.
